# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d950146e9b7f303ee36167b397330019"
name = "qr-code-generator"
handle = "qr-code-generator-78"
application_url = "https://f99e-2804-d51-7456-2400-c1c7-e4b5-db5a-286f.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "arzz-felipe-tests.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://f99e-2804-d51-7456-2400-c1c7-e4b5-db5a-286f.ngrok-free.app/auth/callback",
  "https://f99e-2804-d51-7456-2400-c1c7-e4b5-db5a-286f.ngrok-free.app/auth/shopify/callback",
  "https://f99e-2804-d51-7456-2400-c1c7-e4b5-db5a-286f.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
